# Automation tool - selenium, playwright
automation_tool : 'playwright'
# Browser - chrome, firefox
browser: 'chrome'
browser_options :
  head_less: true
  height: 1200
  width: 800
# Chrome or Firefox path - e.g: '/Users/azazurrehman/Downloads/chromedriver-mac-x64 4/chromedriver'
driver_path: '/Users/azazurrehman/Desktop/work_azaz/pytest_boiler_plate/pytest_boiler_plate/drivers/chromedriver'
# Environment Name
environment_to_execute: 'env1'
# Default wait times (sec)
waits:
  page_load: 120
  element_visible: 60
  element_clickable: 60

